### ISSUE TITLE
Latest release is not at Ansible Galaxy

### ISSUE THREAD

**Issue by northys** [ansible-roles/ansible-role-cron#1]
Hello man,

thank you for your work on this role. It works very well :)

I noticed your latest release is not available on ansible galaxy. Haven't you broken hooks in your repository settings for galaxy?

I really miss your new version which fixes BC breaks in Ansible 2. I know I can install role from Github but I prefer official ansible repository.

Can you please look at it?

Thank you!

**Comment by igormukhingmailcom** [comment]
Hi, @Northys.
Now `v0.3.0` available at https://galaxy.ansible.com/igor_mukhin/cron/

**Comment by northys** [comment]
Thank you a lot for fast resolve!
